### ISSUE TITLE
[Feature request] Block ESP & Tracers

### ISSUE THREAD

**Issue by sebcioxd** [gavinsmod/gavinsextensiblemod#79]
**Is your feature request related to a problem? Please describe.**
The only thing that is missing from this mod is block ESP with tracers, for example when im looking for sugar cane i can easily trace it.

**Describe the solution you'd like**
Adding block ESP & tracers

**Describe alternatives you've considered**
I've tried other popular clients that had the block esp and it was great. But i just prefer more lightweight clients like this one.

**Additional context**
Same feature can be found in popular clients.

**Comment by GT3CH1** [comment]
This is a really cool idea! I'll see if I can do something. I don't imagine it would be difficult to implement on my end, so I'll start drafting up ideas soon. Thanks for the suggestion!

**Comment by GT3CH1** [comment]
Do you also have an example of a client that has a feature like this implemented? I'm curious to see how others have done it. Thanks!

**Comment by sebcioxd** [comment]
Meteor has it and for me worked the best.

**Comment by GT3CH1** [comment]
Hey, I have an update on this - I have a very minimal working version at the moment that doesn't hinder performance. See the picture below! I plan on adding a menu to configure the tracer/esp color and a block selection list, similar to how I have the xray menu sat up (hopefully this isn't awful to do).

![2024-08-31_09 14 16](https://github.com/user-attachments/assets/03d77084-8788-4089-8b55-de2a15b7a5ba)

**Comment by GT3CH1** [comment]
I believe I have finished implementing this - A download is available here: [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc1](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc1). Make sure you download the non-sources jar. This is available for MC 1.21.1 - Please let me know if you find anything weird! If I don't hear back about any feedback/issues in a few days I will go ahead and close this issue and merge it into the main branch. Thanks!

**Comment by sebcioxd** [comment]
Tested it and works fairly well!
I would only add thing - that you can see the block esp behind walls. other than that it works perfectly fine.
Kudos!

**Comment by GT3CH1** [comment]
I've noticed that as well - I believe it's something to do with
iris/sodium/lithium modifying something with how the ESPs are rendered -
are you using any of these mods?

**Comment by sebcioxd** [comment]
Yes, im using sodium and lithium.

**Comment by GT3CH1** [comment]
I've traced the issue down to how sodium manipulates the rendering in
Minecraft, I'm unsure if lithium does something similar - however
uninstalling sodium definitely fixes the ESPs. At this point I'm not super
confident that a solution will be available in the short-term. I'll
continue to look around to see if I can find something though.

**Comment by GT3CH1** [comment]
Well my previous comment was short lived - I have found the issue with my render system. I have written a fix for it and I am migrating all of my ESP/tracers to the new pipeline.

**Comment by GT3CH1** [comment]
Good news, I believe that I have finished working on all the ESP/Tracers to use the new pipeline. I was able to confirm functionality with mods like sodium and iris. I've attached a pic for proof. In this example, I am using sodium and iris with sildurs shaders.

Please download the file `gavinsmod-1.4.8rc2+1.21.1.jar` from the pre-release found here: [https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc2](https://github.com/gavinsmod/gavinsextensiblemod/releases/tag/v1.4.8-rc2)

Let me know if you find anything weird that needs improving!

![image](https://github.com/user-attachments/assets/cfee5b5d-6356-4922-ac8b-acdbf44cbb2e)

**Comment by sebcioxd** [comment]
Everything seems fine! Thank you for implementing this
